apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: karpenter-lab
spec:
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: karpenter
  securityGroupSelectorTerms:
  - tags:
      kubernetes.io/cluster/YOUR_CLUSTER_NAME: owned
  amiSelectorTerms:
  - alias: al2023@latest
  role: "karpenter-YOUR_CLUSTER_NAME-node"
  tags:
    event: karpenter-lab
    autoscaler: karpenter