apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: karpenter-lab-2-whenempty
spec:
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 2m
  template:
    spec:
      requirements:
        - key: "karpenter.k8s.aws/instance-family"
          operator: "In"
          values: [ "m5", "c5", "c5n", "m6g", "m6i", "m6a" ]
        - key: "autoscaler"
          operator: "In"
          values: [ "karpenter" ]
      taints:
        - key: karpenter-nodepool-lab-2
          effect: NoSchedule
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: karpenter-lab