apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-2-karpenter-workload-base
  namespace: karpenter
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: lab-2
        type: base
    spec:
      topologySpreadConstraints:
      - topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        maxSkew: 1
        labelSelector:
          matchLabels:
            name: lab-2
            type: base
      tolerations:
      - key: karpenter-nodepool-lab-2
        effect: NoSchedule
        operator: Exists
      nodeSelector:
        autoscaler: karpenter
      containers:
      - name: karpenter-lab-2
        image: busybox
        command: [ "/bin/sh" ]
        args: [ "-c", "sleep 7200" ]
        resources:
          requests:
              cpu: 500m
              memory: 5Gi
  selector:
    matchLabels:
      name: lab-2
      type: base