apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-2-karpenter-workload-secondary
  namespace: karpenter
spec:
  replicas: 2
  template:
    metadata:
      labels:
        lab: lab-2
        type: secondary
    spec:
      tolerations:
        - key: karpenter-nodepool-lab-2
          effect: NoSchedule
          operator: Exists
      nodeSelector:
        autoscaler: karpenter
      containers:
      - name: karpenter-lab-2
        image: busybox
        command: [ "/bin/sh" ]
        args: [ "-c", "sleep 7200" ]
        resources:
          requests:
              cpu: 500m
              memory: 1Gi
  selector:
    matchLabels:
      lab: lab-2
      type: secondary