apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-1-karpenter-workload
  namespace: karpenter
spec:
  template:
    metadata:
      labels:
        name: lab-1
        autoscaler: karpenter
    spec:
      tolerations:
      - key: karpenter-nodepool-lab-1
        effect: NoSchedule
        operator: Exists
      nodeSelector:
        autoscaler: karpenter
      containers:
      - name: karpenter-lab-1
        image: busybox
        command: [ "/bin/sh" ]
        args: [ "-c", "sleep 7200" ]
        resources:
          requests:
              cpu: 500m
              memory: 5Gi
  selector:
    matchLabels:
      name: lab-1
      autoscaler: karpenter