apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: karpenter-lab-4-c5n-ondemamd
spec:
  template:
    spec:
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: "In"
          values: [ "on-demand" ]
        - key: "karpenter.k8s.aws/instance-family"
          operator: "In"
          values: [ "c5n" ]
        - key: "autoscaler"
          operator: "In"
          values: [ "karpenter" ]
      taints:
        - key: karpenter-nodepool-lab-4
          effect: NoSchedule
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: karpenter-lab