apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-4-evm-workload
  namespace: emp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: lab-4
        type: base
    spec:
      topologySpreadConstraints:
      - topologyKey: node
        whenUnsatisfiable: DoNotSchedule
        maxSkew: 1
      tolerations:
      - key: emp.pf9.io/EMPSchedulable
        effect: NoSchedule
        operator: Exists
      nodeSelector:
        emp.pf9.io/owned: true
      containers:
      - name: karpenter-lab-2
        image: busybox
        command: [ "/bin/sh" ]
        args: [ "-c", "sleep 7200" ]
        resources:
          requests:
              cpu: 500m
              memory: 12Gi
  selector:
    matchLabels:
      name: lab-2
      type: base