apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-3-ondemand-workload
  namespace: karpenter
spec:
  template:
    metadata:
      labels:
        name: lab-3
        autoscaler: karpenter
    spec:
      tolerations:
      - key: karpenter-nodepool-lab-1
        effect: NoSchedule
        operator: Exists
      - key: karpenter-nodepool-lab-3
        effect: NoSchedule
        operator: Exists
      nodeSelector:
        autoscaler: karpenter
        kubernetes.io/arch: arm64
        karpenter.sh/capacity-type: on-demand
      containers:
      - name: karpenter-lab-3
        image: busybox
        command: [ "/bin/sh" ]
        args: [ "-c", "sleep 7200" ]
        resources:
          requests:
              cpu: 500m
              memory: 5Gi
  selector:
    matchLabels:
      name: lab-3
      autoscaler: karpenter